src/Entity/Client.php
<?php

namespace App\Entity;

use App\Repository\ClientRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ClientRepository::class)
 */
class Client
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $surname;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $phone;

    /**
     * @ORM\OneToMany(targetEntity=Booking::class, mappedBy="client")
     */
    private $bookings;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="clients")
     * @ORM\JoinColumn(nullable=false)
     */
    private $school;

    /**
     * @ORM\Column(type="integer")
     */
    private $interview;

    /**
     * @ORM\Column(type="integer")
     */
    private $private_lesson;

    /**
     * @ORM\Column(type="integer")
     */
    private $doneLessons;

    public function __construct()
    {
        $this->bookings = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSurname(): ?string
    {
        return $this->surname;
    }

    public function setSurname(string $surname): self
    {
        $this->surname = $surname;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setClient($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->contains($booking)) {
            $this->bookings->removeElement($booking);
            // set the owning side to null (unless already changed)
            if ($booking->getClient() === $this) {
                $booking->setClient(null);
            }
        }

        return $this;
    }

    public function getSchool(): ?User
    {
        return $this->school;
    }

    public function setSchool(?User $school): self
    {
        $this->school = $school;

        return $this;
    }

    function __toString()
    {
        // TODO: Implement __toString() method.
        return $this->getName().' '.$this->getSurname();
    }

    public function getInterview(): ?int
    {
        return $this->interview;
    }

    public function setInterview(int $interview): self
    {
        $this->interview = $interview;

        return $this;
    }

    public function getPrivateLesson(): ?int
    {
        return $this->private_lesson;
    }

    public function setPrivateLesson(int $private_lesson): self
    {
        $this->private_lesson = $private_lesson;

        return $this;
    }

    public function getDoneLessons(): ?int
    {
        return $this->doneLessons;
    }

    public function setDoneLessons(int $doneLessons): self
    {
        $this->doneLessons = $doneLessons;

        return $this;
    }


}

src/Form/ClientType.php
<?php

namespace App\Form;

use App\Entity\Client;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ClientType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('surname')
            ->add('email')
            ->add('phone')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Client::class,
        ]);
    }
}

src/Controller/ClientController.php
<?php

namespace App\Controller;

use App\Entity\Client;
use App\Entity\LessonNumber;
use App\Form\ClientType;
use App\Repository\ClientRepository;
use App\Service\GeneralService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

/**
 * @IsGranted("ROLE_USER")
 * @Route("/client")
 */
class ClientController extends AbstractController
{
    /**
     * @Route("/", name="client_index", methods={"GET"})
     */
    public function index(ClientRepository $clientRepository, GeneralService $generalService): Response
    {
        return $this->render('client/index.html.twig', [
            //'clients' => $clientRepository->findAll(),
            'clients' => $generalService->getUser()->getClients()
        ]);
    }

    /**
     * @Route("/new", name="client_new", methods={"GET","POST"})
     */
    public function new(Request $request, GeneralService $generalService): Response
    {
        $client = new Client();
        $form = $this->createForm(ClientType::class, $client);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $client->setSchool($generalService->getUser());
            $phone = '+4'.$client->getPhone();
            $client->setPhone($phone);
            $generalService->setInterviewAndPrivateClassNumber($client);
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($client);
            $entityManager->flush();

            return $this->redirectToRoute('client_index');
        }

        return $this->render('client/new.html.twig', [
            'client' => $client,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="client_show", methods={"GET"})
     */
    public function show(Client $client): Response
    {
        return $this->render('client/show.html.twig', [
            'client' => $client,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="client_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Client $client): Response
    {
        $form = $this->createForm(ClientType::class, $client);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('client_index');
        }

        return $this->render('client/edit.html.twig', [
            'client' => $client,
            'form' => $form->createView(),
            'lesson_number' => $this->getDoctrine()->getRepository(LessonNumber::class)->findAll()
        ]);
    }

    /**
     * @Route("/{id}", name="client_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Client $client): Response
    {
        if ($this->isCsrfTokenValid('delete'.$client->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($client);
            $entityManager->flush();
        }

        return $this->redirectToRoute('client_index');
    }

    /**
     * @Route("/add/lessons/{id}", name="client_add_lessons", methods={"GET","POST"})
     */
    public function addPrivateClasses($id)
    {
        $lessonsNumber = $_POST['lessonsNumber'];
        unset($_POST['lessonsNumber']);
        /**
         * @var $client Client
         */
        $client = $this->getDoctrine()->getRepository(Client::class)->find($id);
        $client->setPrivateLesson($client->getPrivateLesson() + $lessonsNumber);
        $this->getDoctrine()->getManager()->flush();
        return $this->redirectToRoute('client_show',[
           'id' => $id
        ]);
    }
}

templates/client/_delete_form.html.twig
<form method="post" action="{{ path('client_delete', {'id': client.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ client.id) }}">
    <button class="btn">Delete</button>
</form>

templates/client/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/client/_lessons.html.twig
<h2>Add Lessons</h2>
<form method="post" action="{{ path('client_add_lessons', {'id': client.id}) }}">
    {% for number in lesson_number %}
        <input type="radio" id="{{ number.id }}" name="lessonsNumber" value="{{ number.value }}">
        <label for="{{ number.id }}">{{ number.value }}</label><br>
    {% endfor %}
    <input type="submit" value="Add private Classes">
</form>

templates/client/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Client{% endblock %}

{% block body %}
    <h1>Edit Client</h1>

    {{ include('client/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('client_index') }}">back to list</a>

    {{ include('client/_delete_form.html.twig') }}

    {{ include('client/_lessons.html.twig') }}
{% endblock %}

templates/client/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Client index{% endblock %}

{% block body %}
    <h1>Client index</h1>

    <input id="myInput" type="text" placeholder="Search..">

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Surname</th>
                <th>Email</th>
                <th>Phone</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody id="myTable">
        {% for client in clients %}
            <tr>
                <td>{{ client.id }}</td>
                <td>{{ client.name }}</td>
                <td>{{ client.surname }}</td>
                <td>{{ client.email }}</td>
                <td>{{ client.phone }}</td>
                <td>
                    <a href="{{ path('client_show', {'id': client.id}) }}">show</a>
                    <a href="{{ path('client_edit', {'id': client.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('client_new') }}">Create new</a>
{% endblock %}

{% block javascripts %}

    <script type="text/javascript">
        $(document).ready(function(){
            $("#myInput").on("keyup", function() {
                var value = $(this).val().toLowerCase();
                $("#myTable tr").filter(function() {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
        });
    </script>

{% endblock %}

templates/client/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Client{% endblock %}

{% block body %}
    <h1>Create new Client</h1>

    {{ include('client/_form.html.twig') }}

    <a href="{{ path('client_index') }}">back to list</a>
{% endblock %}

templates/client/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Client{% endblock %}

{% block body %}
    <h1>Client</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ client.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ client.name }}</td>
            </tr>
            <tr>
                <th>Surname</th>
                <td>{{ client.surname }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ client.email }}</td>
            </tr>
            <tr>
                <th>Phone</th>
                <td>{{ client.phone }}</td>
            </tr>
            <tr>
                <th>Interviews</th>
                <td>{{ client.interview }}</td>
            </tr>
            <tr>
                <th>Private Classes</th>
                <td>{{ client.privateLesson }}</td>
            </tr>
            <tr>
                <th>Done Classes</th>
                <td>{{ client.doneLessons }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('client_index') }}">back to list</a>

    <a href="{{ path('client_edit', {'id': client.id}) }}">edit</a>

    {{ include('client/_delete_form.html.twig') }}
{% endblock %}